### ISSUE TITLE
JOSS submission review #4266 (2nd review)

### ISSUE THREAD

**Issue by RomainAzais** [C0PEP0D/otto#2]
Hi @auroreloisy
I just followed the procedure to install the software in a Conda environment.
The tests generate an error: `ModuleNotFoundError: No module named 'google.protobuf'`
I didn't have any problems with the installation (only some deprecation warnings) and Python 3.8.13 is installed in the env.
(NB: I'm on macOS Big Sur.)
Do you have any idea what's going on?
R.
Review thread: [#4266](https://github.com/openjournals/joss-reviews/issues/4266)

**Comment by auroreloisy** [comment]
Hi  @RomainAzais,
could you try to run the tests one by one to identify which one is broken?
Using
python3 -m pytest tests/test_defaults.py
python3 -m pytest tests/test_heuristicpolicy.py
etc

**Comment by celoy** [comment]
ça ressemble à un problème de tensorflow:

https://stackoverflow.com/questions/39582868/importerror-no-module-named-google-protobuf-but-its-definitely-installed <https://stackoverflow.com/questions/39582868/importerror-no-module-named-google-protobuf-but-its-definitely-installed>

**Comment by auroreloisy** [comment]
(we validated the code with tensorflow 2.8.0)

**Comment by RomainAzais** [comment]
The error occurred in `test_rl.py` and `test_training.py`.
Actually, tensorflow was not installed in the environment even if you mentioned that the dependencies should be installed automatically. (And I said in my first message, no error at the installation.)
I tried several times through conda-forge (`conda install -c conda-forge tensorflow`) but it fails solving the environment.

**Comment by auroreloisy** [comment]
We updated the requirements file to fix the issue, can to try to install otto from scratch again? I was able to reproduce your error, and it seems to work now.

**Comment by RomainAzais** [comment]
👍
It works properly now.

**Comment by RomainAzais** [comment]
Hello!
I think your contribution is very nice. At this stage, I have two questions / comments:
- If I understand well, it is not possible for the user to customize the domain nor the starting location of the MDP and the one of the target (by the way, how are they selected?). I guess it drastically limits the applicability of your code. Am I right? If yes, do you plan to improve the software on this aspect? Maybe it is not your objective, but in that case, you could be more precise on what potential users can expect from it.
- I found the parameter files easy to use, but I was confused with the parameter `LAMBDA_OVER_DX` commented as "dimensionless problem size" in a parameter file and "controls the size the domain" ("of" is missing) in the ReadMe. One can easily understand its effect by testing different values, but do you think you could explain in one line its exact definition (or maybe refer to somewhere in a paper)? (The confusion might come from the name of the variable.)
R.

**Comment by RomainAzais** [comment]
Thank you @auroreloisy for your answer. Indeed, the documentation is clear on this subject and gives the right level of detail in my opinion (not only "the source-tracking POMDP" section, but also "policies" and "deep reinforcement learning" sections).
